name: Commit no PR

on: pull_request

jobs:
  comentario:
    runs-on: ubuntu-latest
    steps:
      - name: Comment na PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Mensagem de teste 1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
